name: main 브랜치에 release path에서 push 했을 경우 태그 추가하기
run-name: Add tag when push release branch to main (${{ github.actor }})

on:
  push:
    branches: "main"

permissions:
  contents: write

jobs:
  add-tag:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: 브런치 이름 조회
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: 버전명으로 치환 및 변수 추가 ( qc-deploy-릴리즈버전-날짜-시간 )
        run: echo "TAG=qc-deploy-$(echo '${{ steps.branch-name.outputs.current_branch }}' | egrep -o '[0-9]*\.[0-9]*\.[0-9]*')-$(echo `date "+%Y%m%d-%H%M"`)" >> $GITHUB_ENV

      - name: 태그 생성
        run: git tag ${{ env.TAG }}

      - name: 태그 푸시
        run: git push origin ${{ env.TAG }}