name: QC 브랜치에 release브랜치 병합되면 태그 및 라벨 추가/삭제하기
run-name: QC 브랜치에 push되면 태그 추가 자동화 (${{ github.actor }})

on:
  pull_request:
    branches:
      - main
    types: [closed]
  
permissions:
  contents: write

jobs:
  add-tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      
      - name: Get current time
        id: current-time
        uses: 1466587594/get-current-time@v2
        with:
          format: YYYYMMDD-HHmm
          utcOffset: "+09:00"

      - name: 버전명으로 치환 및 변수 추가 ( qc-deploy-릴리즈버전-날짜-시간 )
        run: echo "TAG=qc-deploy-$(echo '${{ steps.branch-name.outputs.current_branch }}' | egrep -o '[0-9]*\.[0-9]*\.[0-9]*')-$(echo '${{steps.current-time.outputs.formattedTime}}')" >> $GITHUB_ENV

      - name: 태그 생성
        run: git tag ${{ env.TAG }}

      - name: 태그 푸시
        run: git push origin ${{ env.TAG }}
      
      - name: 확인
        run: echo '${{ github }}'
      
  
  # change-label:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: 8BitJonny/gh-get-current-pr@2.2.0
  #       id: PR
      
  #     - name: set PR
  #       env:
  #         PR_BODY: ${{ steps.PR.outputs.pr_body || github.event.pull_request.body }}
  #       uses: actions/github-script@v6
  #       with:
  #         script: |

  #           console.log("")
  
