name: main 브랜치에 release path에서 push 했을 경우 태그 추가하기
run-name: Add tag when push release branch to main (${{ github.actor }})

on:
  push:
    branches: "main"

jobs:
  branch-name:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_BRANCH_NAME: ${{ steps.check-branch-name.outputs.CURRENT_BRANCH_NAME}}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: check branch name
        id: check-branch-name
        uses: tj-actions/branch-names@v6

      - name: set CURRENT_BRANCH_NAME
        id: branch-name
        run: echo "CURRENT_BRANCH_NAME = ${{ steps.check-branch-name.outputs.current_branch  }}" >> $GITHUB_OUTPUT

      - name: set IS_RELEASE_BRANCH
        run: |
            echo "${{ toJSON(github) }}"
            echo "${{ toJSON(env) }}"
        


