name: main 브랜치에 release path에서 push 했을 경우 태그 추가하기
run-name: Add tag when push release branch to main (${{ github.actor }})

on:
  push:
    branches: "main"

jobs:
  branch-name:
    runs-on: ubuntu-latest

    steps:

      - name: check if release
        run: |
            echo "${{ toJson(github)}}"
            echo "${{ github.ref}}"
            echo "${{ github.head_ref}}"
            echo "${{ github.base_ref}}"
            echo "${{ github.event.ref}}"
            echo "${{ github.event.base_ref}}"



