name: main 브랜치에 release path에서 push 했을 경우 태그 추가하기

on:
  push:
    branches: "main"

jobs:
  branch-name:
    runs-on: ubuntu-latest
    outputs:
      CURRENT_BRANCH_NAME: ${{ steps.check-branch-name.outputs.CURRENT_BRANCH_NAME}}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: check branch name
        id: check-branch-name
        uses: tj-actions/branch-names@v6

      - name: set CURRENT_BRANCH_NAME
        id: current-branch-name
        run: echo "CURRENT_BRANCH_NAME = ${{ steps.check-branch-name.outputs.current_branch }}" >> $GITHUB_OUTPUT

  check-branch:
    runs-on: ubuntu-latest
    needs: branch-name
    env: 
      CURRENT_BRANCH_NAME: ${{ needs.branch-name.outputs.CURRENT_BRANCH_NAME }}
    steps:
      - name: set IS_RELEASE_BRANCH
        id: is-release-branch
        uses: actions/github-script@v6
        with:
          script: |
            const RELEASE = 'release'
            const { CURRENT_BRANCH_NAME } = process.env
            console.log( "process" , process , 'env', process.env)

