name: main 브랜치에 release path에서 push 했을 경우 태그 추가하기
run-name: Add tag when push release branch to main (${{ github.actor }})

on:
  push:
    branches: "main"

jobs:
  branch-name:
    runs-on: ubuntu-latest

    steps:

      - name: check if release
        run: |
            echo "${{ toJSON(github.event.base_ref) }}" || grep 'release'



